### ISSUE TITLE
Error on Windows but not on Ubuntu

### ISSUE THREAD

**Issue by asakhnenko** [NeuralEnsemble/libNeuroML#73]
I am getting a weird error, when I am using the library on Windows (inside Blender software). Although I when I parsed the same file with the same method on Ubuntu, this error didn't occur.  

Traceback (most recent call last):
  File "D:\Blender\2.79\python\lib\site-packages\neuroml\loaders.py", line 38, in __nml2_doc
    nml2_doc = nmlparse(file_name)
  File "D:\Blender\2.79\python\lib\site-packages\neuroml\nml\nml.py", line 22342, in parse
    rootObj.build(rootNode)
  File "D:\Blender\2.79\python\lib\site-packages\neuroml\nml\nml.py", line 14592, in build
    self.buildAttributes(node, node.attrib, already_processed)
  File "D:\Blender\2.79\python\lib\site-packages\neuroml\nml\nml.py", line 14598, in buildAttributes
    super(NeuroMLDocument, self).buildAttributes(node, attrs, already_processed)
  File "D:\Blender\2.79\python\lib\site-packages\neuroml\nml\nml.py", line 5925, in buildAttributes
    value = find_attr_value_('xsi:type', node)
  File "D:\Blender\2.79\python\lib\site-packages\neuroml\nml\nml.py", line 493, in find_attr_value_
    namespace = node.nsmap.get(prefix)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'nsmap'

Do you have any suggestions on how it can be fixed? Thanks in advance

**Comment by vellamike** [comment]
Could you provide some detail about your install method? It looks like you don't have lxml installed on windows.

**Comment by asakhnenko** [comment]
You're right! I thought that since it wasn't an import error, then I should have all the required libraries, but installing lxml library helped. Thanks!
